### ISSUE TITLE
Update Cocoapods

### ISSUE THREAD

**Issue by jyounus** [bugfender/BugfenderSDK-iOS#10]
Hey there,

You need to make sure you update the Cocoapods specs repo as well. Version 0.3.13 is not yet live for me.

https://github.com/CocoaPods/Specs/tree/7d00bbc56276ae581a2c0334cea7ba0d2ea99e41/Specs/BugfenderSDK

Thanks

**Comment by jgimenez** [comment]
Should be there now.
