### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by natanrolnik** [bugfender/BugfenderSDK-iOS#12]
Hi! Is there any place we can see the updated changelog? The one here on GitHub isn't updated since 0.3.10. I'm using 0.3.14, got the log that 0.3.16 is available, but would like to know what's new.

**Comment by jgimenez** [comment]
Hi @natanrolnik , thanks for reporting that. Indeed the release notes were not public but we kept them in an internal document. We will try to keep the GitHub updated from now on. I posted the most important changes also for older versions.

**Comment by natanrolnik** [comment]
Thanks, @jgimenez !
