### ISSUE TITLE
Wrong `There's a new Bugfender SDK version` log message

### ISSUE THREAD

**Issue by natanrolnik** [bugfender/BugfenderSDK-iOS#13]
Hi! I've just updated Bugfender to 0.3.17 (seems to be the most up to date release), and I'm seeing the following log as my app launches:

`There's a new Bugfender SDK version. Please check bugfender.com.`

Also, the ideal would be also to see the number of both versions (current and most up to date) in the log.

**Comment by jgimenez** [comment]
That's right. The compiled version number does not match. We disabled the warning for this version.

We'll consider including the version string in the logs, but it's not easy to do because we work with build numbers not version numbers. We'll consider it anyway because it would be useful.

**Comment by nourahassan** [comment]
I am getting this log on iOS. I am having BugFender using Carthage and the version in the Cartfile.resolved is `1.6.3` which is the latest.

**Comment by jgimenez** [comment]
The file Carthage used was updated, if you delete the downloaded file and try again it will get the right one now.

**Comment by nourahassan** [comment]
Thanks that worked!
