### ISSUE TITLE
Receiving warnings about ending background task

### ISSUE THREAD

**Issue by pellet** [bugfender/BugfenderSDK-iOS#21]
I receive this message from the bugfender sdk framework:
`Can't endBackgroundTask: no background task exists with identifier 16fd8a1a0, or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.`
I'm currently using 0.3.18 and not sure how to update the pod to the latest release... will I have to update the pod using the latest tag?  Not sure if you've fixed this warning yet either :)

**Comment by jgimenez** [comment]
This is a known bug of that library version, we would recommend that you update to the latest one. You can do that by modifying your `Podfile` and setting the version of `BugfenderSDK` to `~>0.3`. Then run `pod update`.

**Comment by pellet** [comment]
Ok glad you fixed the bug, unfortunately pod update does not update the patch version...
I have set pod 'BugfenderSDK', '~> 0.3'
then do a pod update, but still get:
Using BugfenderSDK (0.3.18)
I will use the tag for now to pull down the latest patch version.

**Comment by jgimenez** [comment]
That's correct, our minimum supported version nos is iOS 8. Whilst we did nothing that would prevent earlier versions from working, we do not test under those versions, so we can not tell whether they work properly there.

**Comment by pellet** [comment]
Oh ok, I might have to work out how to override the minimum deployment
level with a pod post processing script
