### ISSUE TITLE
Printing to the console is enabled by default

### ISSUE THREAD

**Issue by mattyohe** [bugfender/BugfenderSDK-iOS#22]
As mentioned in the header, printing to the console is disabled by default:
https://github.com/bugfender/BugfenderSDK-iOS/blob/master/BugfenderSDK.framework/Headers/BugfenderSDK.h#L139-L141

Either the header comment is out of date, or there is unexpected behavior. As of 1.4.1, Bugfender will print to the console by default.

**Comment by jgimenez** [comment]
True @mattyohe, this is a mistake in the documentation since 1.4.0. We will correct it in the next release.

**Comment by jgimenez** [comment]
Fixed in latest release, `1.4.2`.
