### ISSUE TITLE
Bugfender 1.4.2 does not compile with swift 2.3

### ISSUE THREAD

**Issue by hakku276** [bugfender/BugfenderSDK-iOS#24]
Bugfender does not compile with swift 2.3, the compiler error is:
- Bugfender has no member logLineNumber

![screen shot 2017-04-14 at 12 34 07 pm](https://cloud.githubusercontent.com/assets/11570863/25041195/b44aafd4-210e-11e7-8676-00f29e8ee405.png)

**Comment by hakku276** [comment]
I converted this line to -> Bugfender.log(lineNumber:line, method: funcname, file: file, level: BFLogLevel.Default, tag: nil, message: message) and it compiles now!! but i don't know whether it is correct

**Comment by jgimenez** [comment]
Yes, this change is correct. This is due to a change introduced recently in the Swift interface of the method. Thanks for the PR.
