### ISSUE TITLE
Unable to build it in release builds using bitcode

### ISSUE THREAD

**Issue by fpg1503** [bugfender/BugfenderSDK-iOS#26]
I get the following error:
> ▸ Processing Info.plist
> ▸ Compiling Bugfender.swift
> ▸ Compiling Bugfender.swift
> ▸ Compiling BugfenderSDK-dummy.m
> ** ARCHIVE FAILED **
> 
> 
> The following build commands failed:
> Ld /Users/fpg1503/Library/Developer/Xcode/DerivedData/Moobie-bibrrvqdzvgnaocxzyebabsdpjwh/Build/Intermediates/ArchiveIntermediates/Moobie/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/BugfenderSDK.build/Objects-normal/armv7/BugfenderSDK normal armv7
(1 failure)
> ▸ Compiling BugfenderSDK_vers.c
> ▸ Compiling BugfenderSDK-dummy.m
> ▸ Compiling BugfenderSDK_vers.c
> ▸ Linking BugfenderSDK
> ❌  error: Invalid bitcode version (Producer: '802.0.38.0_0' Reader: '800.0.42.1_0')
> ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jgimenez** [comment]
Hi Francesco, it looks like you're not running the latest version of Xcode. Unfortunately we can not embed different versions of bitcode for each version of xcode in the same binary. What you can do is [disable bitcode in your project](http://stackoverflow.com/questions/31205133/how-to-enable-bitcode-in-xcode-7) or update Xcode.

**Comment by fpg1503** [comment]
That being the case do you plan on creating a [SwiftyBeaver] destination that does not depend on your compiled framework?

**Comment by jgimenez** [comment]
No, we do not have that in our plans, sorry.
