### ISSUE TITLE
Link for Swift file returns doc with 404

### ISSUE THREAD

**Issue by mileswright** [bugfender/BugfenderSDK-iOS#28]
Step 4 in the documentation says to use the Bugfender.swift file but that link gives an empty document with 404 inside.  Likely just needs to be updated, current link points here https://raw.githubusercontent.com/bugfender/BugfenderSDK-iOS/master/Swift/Bugfender.swift

4. (If using Swift) Import Bugfender.swift helper file to your project. Add an import BugfenderSDK statement at the top.

**Comment by jgimenez** [comment]
Thanks @mileswright , here's the right file: https://raw.githubusercontent.com/bugfender/BugfenderSDK-iOS/master/swift/Bugfender.swift

**Comment by mileswright** [comment]
Thanks
