### ISSUE TITLE
Experiencing a crash

### ISSUE THREAD

**Issue by miraclebg** [bugfender/BugfenderSDK-iOS#29]
A little bit of a strange crash which has happened to 11 of our users so far.

Any ideas?

Thanks!
[com.teamgymnadz.gymnadz_issue_174_crash_c8d2d3cd252a4ba08fdc9f596cd335b5_b2a013b8893011e7bd9656847afe9799_0_v2.txt](https://github.com/bugfender/BugfenderSDK-iOS/files/1251634/com.teamgymnadz.gymnadz_issue_174_crash_c8d2d3cd252a4ba08fdc9f596cd335b5_b2a013b8893011e7bd9656847afe9799_0_v2.txt)

**Comment by jgimenez** [comment]
Hi @miraclebg , this is something new, we will research what can be happening. Will keep you updated

**Comment by jgimenez** [comment]
Hi @miraclebg , the stacktrace does not correspond to the latest version of Bugfender, but I could not determine which one. We believe this issue is already fixed in the latest version, could you please update to the latest one? Thanks.

**Comment by miraclebg** [comment]
Thanks @jgimenez  but we are installing Bugfender with cocoapods - latest version i see there is:

Using BugfenderSDK (0.3.27)

Is it updated there too?

Should we switch to a manual github dep?

**Comment by miraclebg** [comment]
@jgimenez Thanks, sorted it out!

**Comment by jgimenez** [comment]
Perfect! Happy to help
