### ISSUE TITLE
EXC_BREAKPOINT crash during activateLogger, specifically systemUserAgent

### ISSUE THREAD

**Issue by tahoeWolverine** [bugfender/BugfenderSDK-iOS#32]
Hello,

Wanted to get this out quickly in case others are noticing this. Abruptly at 10am UTC today (7/9/18) our iPad app started crashing during the BugfenderSDK.activateLogger() step, specifically as it calls BFSystemUtils.systemUserAgent internally. It appears that it is running javascript against a webview to determine the user agent and somehow that is causing an EXC_BREAKPOINT exception with not too many helpful details.

Our app, nor our usage of the SDK has changed in ways that would correlate to this abrupt issue spike (3924 instances since 10am UTC); further, the issue does not appear to have happened prior to that time. I suppose it's possible that iOS changed, or that this is a small number of users with some device-specific settings which are causing this.

We have not reproduced the issue internally yet; this is information reported from Fabric/Crashlytics. See below.

Any information would be helpful, thank you!

Mike

----

SDK Version: 1.4.5
iOS Version: 11.4.x (unsure if happening on prior versions)

Crash Log:
[app_crash_c81faa41468a49f9bdd582d9b65f7109_DNE_0_v2.txt](https://github.com/bugfender/BugfenderSDK-iOS/files/2177136/app_crash_c81faa41468a49f9bdd582d9b65f7109_DNE_0_v2.txt)

**Comment by tahoeWolverine** [comment]
Update: At this point, it appears that the crashes have stopped, last one at 16:37:00 UTC. Still curious to figure out why so we can get protection in place to prevent crashes when this scenario occurs.

**Comment by jgimenez** [comment]
Hi @tahoeWolverine, I would recommend updating your SDK to the latest version, where this issue is resolved already.

**Comment by tahoeWolverine** [comment]
Thanks for the response; I will look into it. Would be curious to see the details of the issue and fix, but I understand if that's not readily available.
