### ISSUE TITLE
Invalid bitcode version (Producer: '902.0.39.2_0' Reader: '900.0.39.2_0')

### ISSUE THREAD

**Issue by justjd1992** [bugfender/BugfenderSDK-iOS#33]
SDK version number - 1.5

```
ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '902.0.39.2_0' Reader: '900.0.39.2_0')', using libLTO version 'LLVM version 9.0.0, (clang-900.0.39.2)' for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Getting this error while trying to upload on the app store using **Generic iOS Device** otherwise works properly. Also can't use the solution of disabling Bitcode from Build Settings. Because there would be a chance to reject the application from the app store if set 'Enable Bitcode' to 'No'.   

> export IPHONEOS_DEPLOYMENT_TARGET=8.0
> export PATH="IntermediateBuildFilesPath/Pods.build/Release-iphoneos/BugfenderSDK.build/Objects-normal/armv7/BugfenderSDK

**Comment by jgimenez** [comment]
Hi @justjd1992 as discussed privately the only option is to disable bitcode, since compiled frameworks can not be distributed with different versions of Bitcode

**Comment by NicWickman** [comment]
@jgimenez how do I disable bitcode?

**Comment by jgimenez** [comment]
It depends on how you build the project, but most likely it would be something like this: https://stackoverflow.com/questions/31205133/how-to-enable-bitcode-in-xcode-7

**Comment by quantumpotato** [comment]
I disabled bitcode in project settings and compiled ok.
