### ISSUE TITLE
Add record playback on cloud  service

### ISSUE THREAD

**Issue by MarcSteven** [bugfender/BugfenderSDK-iOS#36]
_Please make sure to inform your SDK version number_.

_If you prefer to contact us privately you can do so at our [support page](http://support.bugfender.com)_

**Comment by jgimenez** [comment]
Hey @MarcSteven , is this a feature request? could you please elaborate?

**Comment by MarcSteven** [comment]
@jgimenez  Yeah ,add the record playback to track the bug easily, glad to submit the requirement ,if error ,pls ignore

**Comment by jgimenez** [comment]
Do you mean a video?

**Comment by jgimenez** [comment]
Whilst we have this in our minds, it's not something we plan to provide anytime soon, since recording video affects _a lot_ the performance of the app

**Comment by MarcSteven** [comment]
@jgimenez  Cool,I found you are a remote company ,if have some remote jobs, pls let me know ,I hope work together with you and then construct a great product ,I am from China ,skilled in mobile development and back-end development using Rails.

**Comment by jgimenez** [comment]
For job applications please check our site, a GitHub issue is not really the place...
