### ISSUE TITLE
Multiple tags

### ISSUE THREAD

**Issue by AndreiVidrasco** [bugfender/BugfenderSDK-iOS#37]
In documentation is specified that I could specify one or multiple tags.
Can you give an example, how to send logs with more than one tag?
https://github.com/bugfender/BugfenderSDK-iOS/blob/30c23493b9ce770c564983116325e22327b1d780/BugfenderSDK.framework/Headers/BugfenderSDK.h#L246

**Comment by RubenVot** [comment]
Hi @AndreiVidrasco , good question. 
This is something we used to have in the long term roadmap but it is not currently implemented. 
We will fix the docs for the next release. 

Can you share a bit why do you need to tag logs with multiple tags? Maybe there is an alternative way that we can recommend. 
Thanks!

**Comment by RubenVot** [comment]
This is an interesting use case @AndreiVidrasco 
I was talking to team today. We think you can accomplish the same behavior just adding different keywords to your logs and filtering the results using the Search field. 
Hopefully in a the future we will be able to add this feature.

**Comment by AndreiVidrasco** [comment]
@RubenVot Search field in my experience is considerable slower than tags. But I will use it as temporary solution.
Thanks
