### ISSUE TITLE
Feedback View Controller Incorrect Behavior

### ISSUE THREAD

**Issue by jeremiahk** [bugfender/BugfenderSDK-iOS#40]
Version 1.6.0
iOS 12.1.1

After the user has filled out the subject field. The keyboard shows a "Done" button. When pressed, the view controller causes a crash. This should be a "Next" button and take the user to the message field.

**Comment by RubenVot** [comment]
Thanks for opening the issue @jeremiahk . Your proposal totally makes sense we will be working on this as soon as possible.

**Comment by RubenVot** [comment]
Solved in https://github.com/bugfender/BugfenderSDK-iOS/releases/tag/1.6.1
