### ISSUE TITLE
carthage update BugfenderSDK-iOS  dosen't build the framework

### ISSUE THREAD

**Issue by yigalomer** [bugfender/BugfenderSDK-iOS#46]
Trying to use your iOS SDK. Added "github "bugfender/BugfenderSDK-iOS" ~>1.6" to my Cartfile and ran update. and getting this error. The framework was not built

➜  Figure8 git:(yigalomer/bugfender) ✗ **carthage update BugfenderSDK-iOS --platform iOS**
*** Fetching RxSwift
*** Fetching SwiftState
*** Fetching MZFormSheetPresentationController
*** Fetching Swift-YouTube-Player
*** Fetching PhoneNumberKit
*** Fetching EasyTipView
*** Fetching unbox
*** Fetching Atributika
*** Fetching MBProgressHUD
*** Fetching SwiftDate
*** Fetching Whisper
*** Fetching R.swift.Library
*** Fetching NextGrowingTextView
*** Fetching SnapKit
*** Fetching RSKImageCropper
*** Fetching libPhoneNumber-iOS
*** Fetching KeychainAccess
*** Fetching Cuckoo
*** Fetching Quick
*** Fetching facebook-objc-sdk
*** Fetching BugfenderSDK-iOS
*** Downloading binary-only framework Instabug at "https://raw.githubusercontent.com/Instabug/Instabug-iOS/master/Instabug.json"
*** Fetching swift-badge
*** Fetching Nimble
*** Fetching LTMorphingLabel
*** Fetching RxGesture
*** Fetching CocoaLumberjack
*** Fetching Alamofire
*** Fetching GzipSwift
*** Fetching AlamofireImage
*** Fetching MZAppearance
*** Checking out BugfenderSDK-iOS at "1.6.6"
*** xcodebuild output can be found in /var/folders/16/vhrg4pcj30xdbps5gyjzvd180000gn/T/carthage-xcodebuild.AxFsN8.log
*** Downloading BugfenderSDK-iOS.framework binary at "1.6.6"
*** Skipped building BugfenderSDK-iOS due to the error:
**Dependency "BugfenderSDK-iOS" has no shared framework schemes for any of the platforms: iOS**

If you believe this to be an error, please file an issue with the maintainers at https://github.com/bugfender/BugfenderSDK-iOS/issues/new

_Please make sure to inform your SDK version number_.

_If you prefer to contact us privately you can do so at our [support page](http://support.bugfender.com)_

**Comment by jgimenez** [comment]
Hi there, we changed the release information so that Carthage can already find the binary in the Github release.

However, we realize we're using the "github" keyword and should be using the "binary" keyword instead, as this is a binary distribution. We also updated the README file to reflect the new recommended way to install Bugfender with Carthage:

```
binary "https://raw.githubusercontent.com/bugfender/BugfenderSDK-iOS/master/BugfenderSDK.json" ~>1.6
```
