### ISSUE TITLE
EXC_BREAKPOINT crash when I call Bugfender.sessionIdentifierUrl()

### ISSUE THREAD

**Issue by nex-derek** [bugfender/BugfenderSDK-iOS#48]
Hi, I'm using version 1.6.6 via Cocoapods. While I setup Bugfender in `application:didFinishLaunchingWithOptions:`, I hit this crash occasionally. Does anyone hit the same issue? Thanks.

![64328308_411573416143205_9121278972011741184_n](https://user-images.githubusercontent.com/31944368/62226570-f5dbfe80-b3ec-11e9-84e5-ca7634abde65.png)

**Comment by jgimenez** [comment]
Hi @nex-derek , I see the `Bugfender.sessionIdentifierUrl()` method actually returns a `URL?` instead of a `URL` as declared, we'll need to fix that.

The nil case can happen when Bugfender has not been activated yet (`Bugfender.activateLogger()` not called), which I don't think is the case here. It would be interesting to see the stacktrace to determine if the error is happening when calling `absoluteString` on a nil object, or rather is something happening inside `sessionIdentifierUrl()`

**Comment by nex-derek** [comment]
Hey @jgimenez , thanks for speedy reply. I agree what you said and I believe that caused by something inside `sessionIdentifierUrl()`. Attached the stacktrace but I don't feel like there is any insight. I've tried to dispatch the call into the main thread and the crash seems disappear. Not sure if it helps your investigation. Thanks!

![67384342_707556399673341_3481525151839813632_n](https://user-images.githubusercontent.com/31944368/62281056-aa266500-b47f-11e9-92ea-b849246b937e.png)
![67896727_465466080698228_1419095265188511744_n](https://user-images.githubusercontent.com/31944368/62281064-ad215580-b47f-11e9-95c9-7afa49ed44b7.png)

**Comment by jgimenez** [comment]
Thanks @nex-derek , this stacktrace confirms the function is returning nil, which shouldn't, because it's of type URL. Maybe the multi-threading thing is a good pointer, our engineers are looking into it

**Comment by nex-derek** [comment]
Looking forward for the fix @jgimenez. Thanks!

**Comment by RubenVot** [comment]
Hi @nex-derek , we just finished the release of the 1.7.0 version in which we have changed how the session id is generated. Your code should work well after you upgrade. 
In the new version you will have to unwrap the sessionIdentifier value. This was needed in the current architecture.  
Thanks a lot for your feedback!

**Comment by nex-derek** [comment]
Thanks @RubenVot, may I know in what cases it will return nil?

**Comment by RubenVot** [comment]
That´s a good question @nex-derek . 
In the new implementation, the identifiers are generated synchronously so the SDK should return null exclusively if you forget to call activateLogger before requesting the session id. 
Let us know if you find any issue using the new version
