### ISSUE TITLE
FRAMEWORK_SEARCH_PATHS overrides project settings

### ISSUE THREAD

**Issue by adubr** [bugfender/BugfenderSDK-iOS#5]
.xcconfig files generated by `pod update' command override FRAMEWORK_SEARCH_PATHS variable which was set on the project level.

project.pbxproj file
```
		4909C9CE17BBB02500A1D331 /* Release */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
[...]
				FRAMEWORK_SEARCH_PATHS = "$(PROJECT_DIR)/MyProject/Frameworks";
[...]
			};
			name = Release;
		};

```

Pods.*.xcconfig files
```
FRAMEWORK_SEARCH_PATHS = $(PODS_ROOT)/BugfenderSDK
```

**Comment by jgimenez** [comment]
Thanks for reporting. Will look into it promptly!

**Comment by jgimenez** [comment]
Should be fixed by now, please report if you find further problems!

**Comment by adubr** [comment]
@jgimenez thanks for a quick response!
Unfortunately the bug still persists somehow.
Have no idea where `FRAMEWORK_SEARCH_PATHS = "$(PODS_ROOT)/BugfenderSDK"` in Pods.*.xcconfig files comes from now. 

Here's my Podfile
```
platform :ios, '7.0'
pod 'Reachability',  '~> 3.0.0'
pod 'AFNetworking', '~> 1.3.2'
pod 'GoogleAnalytics-iOS-SDK', '~>3.0.6'
pod 'Block-KVO', :git => 'https://github.com/iMartinKiss/Block-KVO.git', :tag => 'v2.2.3'
pod 'BugfenderSDK', :git => 'https://github.com/bugfender/BugfenderSDK-iOS.git', :tag => '0.3.4'

target :UnitTests, :exclusive => true do
  link_with 'MyProjectTests'

  pod 'Specta',      '~> 1.0.0'
  pod 'Expecta',     '~> 1.0.0'   # expecta matchers
  # pod 'OCMock',      '~> 2.2'   # OCMock
  # pod 'OCHamcrest',  '~> 3.0'   # hamcrest matchers
  pod 'OCMockito',   '~> 1.0'   # OCMock
  # pod 'LRMocky',     '~> 0.9'   # LRMocky
end
```

**Comment by jgimenez** [comment]
Will check again, thanks for the sample.

**Comment by jgimenez** [comment]
Hi @adubr, I've given a second look at that (sorry for the delay). Apparently it works the other way around: CocoaPods generates a FRAMEWORK_SEARCH_PATHS, and then in the project you have the possibility to override it. Probably you want to have your own plus the ones that come with CocoaPods.

Here's how to do it:
http://stackoverflow.com/questions/26445784/target-overrides-the-framework-search-paths-build-settings

Does that work for you?

**Comment by adubr** [comment]
Well, it does work, and currently this is why my project does compile. But I'd like to set up the paths on the **project** level, not on the target one. Bugfender pod overrides the **project** setting. No other pod that I'm using (see above) does this.
Not sure if it helps, but the `Pods*.xcconfig` files for the test target contain the following

```
FRAMEWORK_SEARCH_PATHS = $(inherited) $(DEVELOPER_FRAMEWORKS_DIR) "$(PLATFORM_DIR)/Developer/Library/Frameworks" "$(DEVELOPER_DIR)/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks" "$(SDKROOT)/Developer/Library/Frameworks" $(inherited) $(DEVELOPER_FRAMEWORKS_DIR) "$(PLATFORM_DIR)/Developer/Library/Frameworks" "$(DEVELOPER_DIR)/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks" "$(SDKROOT)/Developer/Library/Frameworks"
```

which apparently respects the project-level settings

**Comment by jgimenez** [comment]
I'm sorry @adubr but this is a decision taken by CocoaPods team. I get your point and I think you should open an issue with them.

I guess you can always import the Bugfender framework manually if CocoaPods doesn't fit your needs.
