### ISSUE TITLE
BFLog function seems to not exist in 1.8.0 using cocoapods

### ISSUE THREAD

**Issue by mcmurrym** [bugfender/BugfenderSDK-iOS#51]
BFLog function seems to not exist in 1.8.0 using cocoapods

**Comment by RubenVot** [comment]
Hi @mcmurrym thanks for reporting, let me investigate that.

**Comment by RubenVot** [comment]
Hi @mcmurrym looks like cocoapods is pointing to the incorrect commit. We are going to fix that as soon as possible but meanwhile, if this is a blocker for you, you should be able to point to github like this:  
```
pod 'BugfenderSDK', :git => 'https://github.com/bugfender/BugfenderSDK-iOS' , :branch => "master"
```
Thanks a lot for the report and sorry for the inconvenience.

**Comment by RubenVot** [comment]
This should be fixed. Just to be sure you get the correct version please apply: 
```
pod cache clean ‘BugfenderSDK’ --all
pod install
``` 
Let us know if you have any other issue
