### ISSUE TITLE
BugfenderSDK.h is missing in XCFramework

### ISSUE THREAD

**Issue by rodmaz** [bugfender/BugfenderSDK-iOS#53]
SDK Version 1.9.0

`BugfenderSDK.h` header file is missing from XCFramework even though module map file `module.modulemap` points to it:

```
framework module BugfenderSDK {
  umbrella header "BugfenderSDK.h"

  export *
  module * { export * }
}

module BugfenderSDK.Swift {
    header "BugfenderSDK-Swift.h"
    requires objc
}
```

**Comment by RubenVot** [comment]
That's curious, we have the building automated and it was correctly copied to the framework, not sure what happened here. Anyway, we are working on this release. Hopefully will be working next week. 
Thanks a lot for the report @rodmaz !

**Comment by RubenVot** [comment]
We had an old rule in the gitignore preventing to push the header. 
Should be fixed now.
