### ISSUE TITLE
Swift 5.2 support?

### ISSUE THREAD

**Issue by pykaso** [bugfender/BugfenderSDK-iOS#54]
Hi, I'm getting this error with the new version of Xcode 11.4

*** Downloading BugfenderSDK-iOS.framework binary at "1.9.0"
***  Skipped installing BugfenderSDK-iOS.framework binary due to the error:
	"Incompatible Swift version - framework was built with 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9) and the local version is 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)."

    Falling back to building from the source
*** Skipped building BugfenderSDK-iOS due to the error:
Dependency "BugfenderSDK-iOS" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/bugfender/BugfenderSDK-iOS/issues/new

**Comment by jgimenez** [comment]
Hi @pykaso , how are you installing the framework? Is this an error message by Carthage?

**Comment by RubenVot** [comment]
Hi @pykaso unfortunately this looks like a problem with Carthage https://github.com/Carthage/Carthage/issues/2887 
As of Swift 5.1 the ABI stability should allow you to install Bugfender built with different Swift versions. 
Closing for now. Let us know if it doesn't work for you.

**Comment by sam-w** [comment]
@pykaso and for anyone watching this issue, the problem should now be fixed with the release of Carthage 0.35.0
