### ISSUE TITLE
No statically linked library 

### ISSUE THREAD

**Issue by deathlyrage** [bugfender/BugfenderSDK-iOS#56]
Unreal Engine 4 needs to use a static linked library / framework and there is no source code to compile it yourself and use this. I have to use a extremely old version that is when unity supported statically linked versions only.

Please provide a statically linked version in the github releases or the source code so I can build it myself thanks.

**Comment by RubenVot** [comment]
Hi @deathlyrage we changed to dynamic framework to support the new features of ios 13 and the new xcframeworks. 
You can use [Bugfender 1.7](https://github.com/bugfender/BugfenderSDK-iOS/releases/tag/1.7.0) which has almost the same features than the last version. However, I understand your point, I will discuss internally the possibility to add a static library with the next releases.

**Comment by jgimenez** [comment]
Hi @deathlyrage . In addition, I would suggest opening a bug with Unreal Engine if it's really not possible to use a dynamic framework, because that's the way frameworks are now distributed, because of various benefits, including support for Swift. I'm more inclined to think there must be a way to do it, although maybe it's not well documented yet.

**Comment by deathlyrage** [comment]
> Hi @deathlyrage we changed to dynamic framework to support the new features of ios 13 and the new xcframeworks.
> You can use [Bugfender 1.7](https://github.com/bugfender/BugfenderSDK-iOS/releases/tag/1.7.0) which has almost the same features than the last version. However, I understand your point, I will discuss internally the possibility to add a static library with the next releases.

This would be amazing because I don't see the UE4 team adding support for frameworks anytime this year. There are heaps of bug reports / issues open for other customers and Unreal Engine recommends just switching to middleware that can be provided as a static lib. 

Long term a better solution for you guys might be working with Epic Games to get this added, or put out a plugin on the unreal engine marketplace that adds Bugfender support.  They can even cover the costs of doing this with a dev grant.

**Comment by deathlyrage** [comment]
Any updates on the next release including this?

**Comment by RubenVot** [comment]
Hi @deathlyrage it is in our backlog and we already started internal discussions about this. 
We will close this issue when we add it. 
Thanks.

**Comment by RubenVot** [comment]
Hi @deathlyrage we are starting share a static lib with our beta testers and the users that requested it. Would you be willing to test it in Unreal Engine and let us know if this version works for you? We don't have any game developer in house so your feedback would be very much appreciated :) 
[Static library link](https://github.com/bugfender/BugfenderSDK-iOS/releases/download/1.9.2/BETA.StaticLib.zip)

**Comment by deathlyrage** [comment]
Works amazing thanks!

**Comment by RubenVot** [comment]
Happy to know it helped. 
We will try to distribute an updated version with our future releases
