### ISSUE TITLE
No such module 'BugfenderSDK'

### ISSUE THREAD

**Issue by pepejeria** [bugfender/BugfenderSDK-iOS#59]
Steps to reproduce:

1. Create new project in Xcode Version 12.0 (12A7209)
2. Setup cocoapods using Cocoapods 1.10.0.rc.1 
3. Add pod 'BugfenderSDK' to the Podfile and run pod install (install version 1.9.2 of BugfenderSDK)
4. Add `import BugfenderSDK` to any Swift file 
5. Change theme to use `Release` configuration 
6. Build project 

This will result in an error:
No such module 'BugfenderSDK'

Project builds fine when using the `Debug` configuration.

**Comment by pepejeria** [comment]
Downgraded to cocoapods 1.9.3 and go the following error instead:

```
Failed to build module 'BugfenderSDK' from its module interface; the compiler that produced it, 'Apple Swift version 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)'
```

**Comment by RubenVot** [comment]
Hi @pepejeria 
Thanks a lot for reporting we will take a look.

**Comment by RubenVot** [comment]
Hi @pepejeria we just uploaded an update to our beta branch. By internal policy we must run a full battery of tests and update a few things in the server before I can move the new version of Bugfender **1.9.3** to master, but no changes are expected, you should be safe using this branch. Along the next week you can come back to master.
`pod 'BugfenderSDK', :git => 'https://github.com/bugfender/BugfenderSDK-iOS' , :branch => "beta"` 
Will close this issue when we finish the release. 
Thanks!

**Comment by pepejeria** [comment]
Great, thank you for fixing this so quickly. 🙏

**Comment by pepejeria** [comment]
This was working but it is broken again. I am using the build from the beta branch as suggested and get the following error:

```
Selected xcframework slice ios-i386_x86_64-simulator/BugfenderSDK.framework
/Volumes//Users/user/SomeProject/Pods/Target Support Files/Pods-SomeProject/Pods-SomeProject-artifacts.sh: line 61: source: unbound variable
```

**Comment by pepejeria** [comment]
`pod deintegrate` and `pod install` solved the issue.

**Comment by RubenVot** [comment]
Great. 
If it fails again you can also go to the _Product_ menu in Xcode and click on _Clean_ while pressing _option key_ ( Clean Build Folder)

**Comment by pepejeria** [comment]
I am getting this every time that I do a `pod update`. Option clicking Clean does not solves the problem. Only solution is to run `pod deintegrate` and `pod install`. Do you have plans to release 1.9.3 soon-ish?

**Comment by RubenVot** [comment]
Hi @pepejeria I don't think this an issue with Bugfender but a bug in Cocoapods. My guess is that pod update is messing the header search paths but there's nothing we can do about it. Once they release their new version we can double check and run more (that's basically what we are waiting to release 1.9.3). 
Anyway, Bugfender doesn't need cocoapods, you can just drop de xcframework in your app if you need to debug.

**Comment by pepejeria** [comment]
fyi: cocoapods 1.10.0 has been released.

**Comment by RubenVot** [comment]
Pushed Bugfender 1.10.0 to beta branch. 
Testing now

**Comment by RubenVot** [comment]
Released
