### ISSUE TITLE
When installing BugfenderSDK through CocoaPods

### ISSUE THREAD

**Issue by billylo1** [bugfender/BugfenderSDK-iOS#6]
[!] Unable to read the license file `/Users/billylo/Xcode/Mayday2/MaydayApp/Pods/BugfenderSDK/See http://bugfender.com/terms-of-service/` for the spec `BugfenderSDK (0.3.5)`

**Comment by jgimenez** [comment]
Thanks for reporting @billylo1 . It has been fixed for the next version.
