### ISSUE TITLE
Several users / instances of Bugfender

### ISSUE THREAD

**Issue by AlexGerm** [bugfender/BugfenderSDK-iOS#62]
I want to use Bugfender in my framework which is integrated with apps via Cocoapods and I have BugfenderSDK dependency in a podspec. I activate logger with `Bugfender.activateLogger` method in one of my public classes. 
What if users who integrate the framework also use Bugfender? Will their logs appear in my account or my logs in theirs? Is it possible to separate accounts in code?

**Comment by RubenVot** [comment]
Hi @AlexGerm, 
I don't think that's possible at the moment because Bugfender's public API is a singleton. If you try to call activateLogger twice Bugfender will throw an exception.
