### ISSUE TITLE
XCFramework download link is broken in SwiftPM

### ISSUE THREAD

**Issue by akolov** [bugfender/BugfenderSDK-iOS#66]
Right now binary target url in the Package.swift is pointing to `https://github.com/bugfender/BugfenderSDK-iOS/releases/download/1.10.1/BugfenderSDK.xcframework.zip` which is not available and hence updating packages results in broken dependency.

**Comment by jgimenez** [comment]
It should now be available, we're still doing the release

**Comment by jgimenez** [comment]
Confirmed, it's available
