### ISSUE TITLE
Bugfender is not updated in CocoaPods

### ISSUE THREAD

**Issue by iskalinov13** [bugfender/BugfenderSDK-iOS#68]
Bugfender is not updated in CocoaPods. Current version is 1.10.1 but in production don't have 1.10.2 
Please update your pod speck files.

**Comment by jgimenez** [comment]
Bugfender is already updated in Cocoapods: https://cocoapods.org/pods/BugfenderSDK

Cocoapods uses CDNs and caching, so sometimes it might take a few hours before it's visible.
