### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by RadekZmeskalAddai** [bugfender/BugfenderSDK-iOS#72]
I have problem with Bugfender framework.
I install Bugfender via Cocoapods. I shoud have version 1.10.3.

My app is crashing sometimes, when it's sending logs with Bugfender.
I have no idea how to replicate it, because logs are not send.

I am attaching log from Crashlytics.

<img width="694" alt="bugfender" src="https://user-images.githubusercontent.com/73204951/136796226-c257f69e-facf-4009-81c4-be5e1fc1aa26.png">

**Comment by jgimenez** [comment]
That's the problem, then. If you change the logging line to `BFLogInfo("%@", logRequest)` you'll be ace. The first argument must be a format string, it can not be an already formatted string.

You can also use `bfprint(logRequest)`, which works in a way similar to Swift's `print()` that maybe you're more familiar with.
