### ISSUE TITLE
Bugfender iOS SDK crashes on 1.10.3

### ISSUE THREAD

**Issue by hanumanAbacus** [bugfender/BugfenderSDK-iOS#77]
BugfenderSDK 1.10.3

<img width="1267" alt="Screen Shot 2022-03-21 at 9 44 21 am" src="https://user-images.githubusercontent.com/42829607/159189290-d8d0699c-52f6-429c-861d-1e99acfb4729.png">

**Comment by jgimenez** [comment]
Hi there, this is a known issue for a previous version of BugfenderSDK, but not known for 1.10.3. Are you sure this is 1.10.3? If you are, please provide the full crash report so we can look into it. You can do it here or via support.

**Comment by jgimenez** [comment]
Closing stale issue.
