### ISSUE TITLE
Crash *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]

### ISSUE THREAD

**Issue by hanumanAbacus** [bugfender/BugfenderSDK-iOS#78]
1.10.5

*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]
Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]'

Thread 0 Crashed:
0   CoreFoundation                  0x000000019522f794 0x195105000 + 1222548
1   libobjc.A.dylib                 0x0000000194f51bcc objc_exception_throw + 56
2   CoreFoundation                  0x00000001952852dc 0x195105000 + 1573596
3   CoreFoundation                  0x000000019528e744 0x195105000 + 1611588
4   CoreFoundation                  0x000000019511d1fc 0x195105000 + 98812
5   CoreFoundation                  0x000000019510f204 0x195105000 + 41476
6   BugfenderSDK                    0x0000000105eaa628 __51-[BFCrashReportingSink filterReports:onCompletion:]_block_invoke.10 + 904
7   CoreFoundation                  0x0000000195202e20 0x195105000 + 1039904
8   CoreFoundation                  0x0000000195106d4c 0x195105000 + 7500
9   BugfenderSDK                    0x0000000105eaa05c -[BFCrashReportingSink filterReports:onCompletion:] + 376
10  BugfenderSDK                    0x0000000105e5e2bc -[BFSDK_KSCrash sendReports:onCompletion:] + 220
11  BugfenderSDK                    0x0000000105e5ddac -[BFSDK_KSCrash sendAllReportsWithCompletion:] + 212
12  BugfenderSDK                    0x0000000105ea9e44 -[BFCrashReportingManager sendAllReports] + 140
13  libdispatch.dylib               0x0000000194ef5524 0x194e9a000 + 374052
14  libdispatch.dylib               0x0000000194e9de98 0x194e9a000 + 16024
15  libdispatch.dylib               0x0000000194eae430 0x194e9a000 + 82992
16  libdispatch.dylib               0x0000000194ea7498 0x194e9a000 + 54424
17  CoreFoundation                  0x00000001951ad7fc 0x195105000 + 690172
18  CoreFoundation                  0x00000001951a86d0 0x195105000 + 669392
19  CoreFoundation                  0x00000001951a7ce8 CFRunLoopRunSpecific + 424
20  GraphicsServices                0x000000019f2f238c GSEventRunModal + 160
21  UIKitCore                       0x00000001992d6444 UIApplicationMain + 1932
22  Abacus                          0x00000001030f0af8 0x102e70000 + 2624248
23  libdyld.dylib                   0x000000019502f8f0 0x19502e000 + 6384

**Comment by jgimenez** [comment]
Update: this was fixed in version 1.10.6.
