### ISSUE TITLE
1.10.6 breaks builds using xcode 13

### ISSUE THREAD

**Issue by rocketraman** [bugfender/BugfenderSDK-iOS#80]
When using 1.10.6, my build on XCode 13 fails with:

![image](https://user-images.githubusercontent.com/53049/207133556-f41caeec-2053-457c-8408-851ba907ff82.png)

Presumably a backwards incompatible change like this should not have been released with a minor version number?

**Comment by jgimenez** [comment]
Hi @rocketraman , probably we updated the Xcode version without realizing this would affect people who stayed on the old version. The API of the library itself is not breaking, so if you upgrade Xcode everything should work as usual.

Unfortunately, I guess there is nothing we can do now, so we'll take it into account for next versions.

**Comment by rocketraman** [comment]
Yeah you're not the only ones. This is Apple being silly unfortunately. Thanks for keeping it in mind for the future.
