### ISSUE TITLE
release tag 1.12.0 `.xcframework.zip` file missing

### ISSUE THREAD

**Issue by dxmvsh** [bugfender/BugfenderSDK-iOS#82]
Currently in project we are fetching SDK up to next major starting from 1.10.0.
Found out our CI machine is failing builds for couple of hours by not being able to download required `.xcframework.zip` file. 
Below is the log keeping popping up:
`failed downloading 'https://github.com/bugfender/BugfenderSDK-iOS/releases/download/1.12.0/BugfenderSDK.xcframework.zip' which is required by binary target 'BugfenderSDK': badResponseStatusCode(404)`

The problem is in the release tag 1.12.0, where `.xcframework.zip` file is missing, but format alike files had been uploaded for previous releases. Hope in the future it will be considered that all files are uploaded before pushing new release tag. 

As a workaround, set exact version of SDK to 1.11.0.

**Comment by franmontiel** [comment]
@dxmvsh thanks for the report.
The xcframework.zip and the rest of the zip files are now available again.
Sorry for the inconvenience.
