### ISSUE TITLE
Privacy manifest file is missing required reason for disk space APIs

### ISSUE THREAD

**Issue by vlvs** [bugfender/BugfenderSDK-iOS#85]
Although the [PrivacyInfo.xcprivacy](https://github.com/bugfender/BugfenderSDK-iOS/blob/main/BugfenderSDK.framework/PrivacyInfo.xcprivacy) has already been implemented and released, its only describing the required reason for `NSPrivacyAccessedAPICategoryUserDefaults`, but it looks like Bugfender also needs to add a reason for `NSPrivacyAccessedAPICategoryDiskSpace`.

```
Used symbols in binary ./***/Pods/BugfenderSDK/BugfenderSDK.xcframework/ios-arm64_x86_64-simulator/BugfenderSDK.framework/BugfenderSDK: NSFileSystemSize, NSUserDefaults
Used symbols in binary ./***/Pods/BugfenderSDK/BugfenderSDK.xcframework/ios-arm64_x86_64-maccatalyst/BugfenderSDK.framework/BugfenderSDK: NSFileSystemSize, NSUserDefaults
Used symbols in binary ./***/Pods/BugfenderSDK/BugfenderSDK.xcframework/ios-arm64/BugfenderSDK.framework/BugfenderSDK: NSFileSystemSize, NSUserDefaults
```

This was found by scanning the project with the following script: [required_reason_api_binary_scanner.sh](https://github.com/Wooder/ios_17_required_reason_api_scanner/blob/main/required_reason_api_binary_scanner.sh)

**Comment by jgimenez** [comment]
Hi, if you do not have any further input, we'll close this for now. Please feel free to reopen if you feel this is still a problem.
